#===========================================================================#
# ██╗  ██╗██╗████████╗████████╗██╗   ██╗ ██████╗ ██████╗ ███╗   ██╗███████╗ #
# ██║ ██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝██╔════╝██╔═══██╗████╗  ██║██╔════╝ #
# █████╔╝ ██║   ██║      ██║    ╚████╔╝ ██║     ██║   ██║██╔██╗ ██║█████╗   #
# ██╔═██╗ ██║   ██║      ██║     ╚██╔╝  ██║     ██║   ██║██║╚██╗██║██╔══╝   #
# ██║  ██╗██║   ██║      ██║      ██║██╗╚██████╗╚██████╔╝██║ ╚████║██║      #
# ╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝      #
#===========================================================================#                                                                         


#====================#
#      FEATURES      #
#====================#

copy_on_select yes



#====================#
# Font configuration #
#====================#

font_family JetBrainsMono NF
font_size 12.0



#=========#
# keymaps #
#=========#
map Ctrl+plus increase_font_size
map Ctrl+minus decrease_font_size
map Ctrl+Shift+C copy_selection_to_clipboard
map Ctrl+Shift+V paste_from_clipboard



#==============#
# kitty-window #
#==============#
window_margin_width 20



#=============#
# kitty-theme #
#=============#
include /home/eden/.cache/wal/colors-kitty.conf
